# kaniko-job/kaniko-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - --context=dir:///workspace
        - --dockerfile=Dockerfile  # This should not include the /workspace prefix
        - --destination=devsp2020/hello-world:latest
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      restartPolicy: Never
      volumes:
      - name: workspace
        hostPath:
          path: /Users/snehaloffice/Dev/Code/K8s/hello-world-app  # Ensure this path is correct
